[package]
name = "flint3-sys"
description = "Rust bindings to the FLINT C library"
version = "3.6.1"
repository = "https://github.com/lairez/flint3-sys"
edition = "2021"
links = "flint"
authors = ["Pierre Lairez"]
license = "MIT"
categories = ["external-ffi-bindings", "mathematics"]
keywords = ["computer-algebra"]
build = "build/main.rs"

[features]
default = []
run-bindgen = ["dep:bindgen", "dep:regex", "dep:tempfile"]
gmp-mpfr-sys = ["dep:gmp-mpfr-sys"]
use-system-libs = ["dep:pkg-config"]

[dependencies]
gmp-mpfr-sys = { version = "1.7.1", optional = true }
libc = "0.2.186"

[dev-dependencies]
tempfile = "3.27.0"

[build-dependencies]
anyhow = "1.0.98"
bindgen = { version = "0.72.1", optional = true }
cc = "1.2.23"
pkg-config = { version = "0.3", optional = true }
regex = { version = "1.11.1", default-features = false, features = ["std"], optional = true }
tempfile = { version = "3.27.0", optional = true }

[target.'cfg(target_env = "msvc")'.build-dependencies]
cmake = "0.1.58"
vcpkg = "0.2.15"

[package.metadata.docs.rs]
features = ["gmp-mpfr-sys"]     # docs.rs does not have libgmp-dev
